const { LinkedList } = require("./dist/LinkedList");

let list = LinkedList.create(1, 2, 3, 4, 5, 6);
console.log('--------------------------------------------------------');
console.log('Current list:', list.print());
console.log('Middle node:', list.middle().show);
console.log('Node at index 4:', list.nodeAt(4).show);
console.log('List size:', list.size);
console.log('Array:', list.toArray());
console.log('--------------------------------------------------------');
list.reverse();
console.log('list reversed...');
console.log('Current list:', list.print());
console.log('Middle node:', list.middle().show);
console.log('Node at index 2:', list.nodeAt(2).show);
console.log('List size:', list.size);
console.log('Array:', list.toArray());
console.log('--------------------------------------------------------');
let subList = list.subList(2, 4);
console.log(subList.print());